### ISSUE TITLE
[TRACKING ISSUE] Fix class definitions registration with same class id [API-1260]

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-go-client#505] opened 2021-01-26 15:49 UTC
The tracking issue for the Java side PR.

**Fix class definitions registration with same class id**

See https://github.com/hazelcast/hazelcast/pull/16831 for details.

---

When class definition is registered explicitly from serialization config
, if user gives same class id in different factories, we could not
handle it correctly. This pr makes sure it works from now on.

fixes https://github.com/hazelcast/hazelcast/issues/16820

(cherry picked from commit 29b1fb3ad3f29e78757d472ab827bb0b222b39ad)

**Comment by srknzl** [comment] 2021-09-07 08:59
fyi this is duplicate of https://github.com/hazelcast/hazelcast-go-client/issues/480

**Comment by yuce** [comment] 2021-09-20 12:07
Thanks @srknzl !

**Comment by yuce** [comment] 2021-09-20 12:08
Check whether a test exists for this.

**Comment by yuce** [comment] 2022-03-04 11:53
Closing, duplicate of https://github.com/hazelcast/hazelcast-go-client/issues/480

**Closed by yuce** 2022-03-04 11:53 UTC
Labels: to-jira, Investigate
