### ISSUE TITLE
ringbuffer and reliable topic marked as implemented, but isn't

### ISSUE THREAD

**Issue by willie68** [hazelcast/hazelcast-go-client#751] opened 2022-03-15 13:04 UTC
Go version: 1.16
Hazelcast Go Client version: 1.1.1
Hazelcast server version: 5.1
Number of the clients: x
Cluster size, i.e. the number of Hazelcast cluster members: 3
OS version : Kubernetes/Linux/Alpine:3.12

In the Chart "Features Implemented for this Client" Reliable Topic (as RIngbuffer) is marked as implemented (https://hazelcast.com/clients/go/#client-features)
however, the reliable topic is not implemented in the current client implementation. (The same applies to the ring buffer)

Is there a time horizon for when ring buffers and reliable topics will be implemented?

**Comment by yuce** [comment] 2022-08-03 01:42
Duplicate of https://github.com/hazelcast/hazelcast-go-client/issues/674, closing.

**Closed by yuce** 2022-08-03 01:42 UTC
