### ISSUE TITLE
Lots of created and destroy clients use lots of CPU

### ISSUE THREAD

**Issue by roidelapluie** [hazelcast/hazelcast-go-client#412] opened 2018-12-28 23:16 UTC
Go version:
Hazelcast Go Client version:
master
Hazelcast server version:
3.11
Number of the clients:
1 at the time

Cluster size, i.e. the number of Hazelcast cluster members:
1 or 2

OS version : Linux

#### Expected behaviour

I can do a client, err := hazelcast.NewClientWithConfig(config)
and  a client.Shutdown()

thousands of times.

#### Actual behaviour

When I do this, the process is using more processor over time.

Seems related to timers.

[profile-cpu.zip](https://github.com/hazelcast/hazelcast-go-client/files/2715842/profile-cpu.zip)

**Comment by yuce** [comment] 2021-05-12 07:05
@roidelapluie Thanks for reporting this. I've added a benchmark to the new codebase for client start/shutdown. It seems we can start/shutdown clients over 260 times in a second, 1300 times in 5 seconds and 2600 times in 10 seconds, which looks pretty linear. The number of client start/stop cycles don't seem to affect CPU usage over time, so I think we don't have the problem anymore with the new codebase. Closing this issue, but feel free to reopen it in case the problem is not resolved for you with the new client codebase.

**Closed by yuce** 2021-05-12 07:05 UTC
Labels: Priority: High, Type: Defect
